### ISSUE TITLE
zdem2jpg时，采用--wallshow=false，xmax ymax失效。

### ISSUE THREAD

**Issue by demsheng** [geovbox/zdem_doc#10]
- 测试命令 
  ```
  zdem2jpg --dir=./data  --xmove=-1000 --ymove=-1000 --xmin=0 --ymin=0 --xmax=40000 --ymax=10000 --wallshow=false
  ```
- 测试脚本 `push_add_del.py` 见 https://doc.geovbox.com/latest/strainstress/add_del/#ex-strain-stress
- 绘图结果：
![all_0000000000_ini](https://user-images.githubusercontent.com/16026136/120225719-4e45e680-c278-11eb-8668-0aefccf8402d.jpg)
![all_0000001000](https://user-images.githubusercontent.com/16026136/120225724-51d96d80-c278-11eb-839c-d9b81d330270.jpg)

**Comment by geovbox** [comment]
V2.1已修复。
